// <auto-generated />
using System;
using EnterpriseAeroStudio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseAeroStudio.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910115842_AddCarCreditNumber")]
    partial class AddCarCreditNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("EnterpriseAeroStudio.Models.CarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AlisQiymeti")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlisSaati")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AlisTarixi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Il")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KreditNomresi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("QeydiyyatNisani")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Yanacaq")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Yurus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QeydiyyatNisani");

                    b.ToTable("Avtomobiller", (string)null);
                });

            modelBuilder.Entity("EnterpriseAeroStudio.Models.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AylıqOdenis")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BaslamaTarixi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FaizDerecesi")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mebleg")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("MuddetAy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MuqavileNomresi")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mustəri")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Qeyd")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Kreditler", (string)null);
                });

            modelBuilder.Entity("EnterpriseAeroStudio.Models.CreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreditId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Mebleg")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nov")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tesvir")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreditId");

                    b.ToTable("KreditEmeliyyatlari", (string)null);
                });

            modelBuilder.Entity("EnterpriseAeroStudio.Models.ExpenseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kategoriya")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mebleg")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("OdenisUsulu")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Qeyd")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Qrup")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("TEXT");

                    b.Property<string>("Teyinat")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("Tarix");

                    b.HasIndex("Teyinat");

                    b.ToTable("Xercler", (string)null);
                });

            modelBuilder.Entity("EnterpriseAeroStudio.Models.Credit", b =>
                {
                    b.HasOne("EnterpriseAeroStudio.Models.CarItem", "Car")
                        .WithMany("Credits")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Car");
                });

            modelBuilder.Entity("EnterpriseAeroStudio.Models.CreditTransaction", b =>
                {
                    b.HasOne("EnterpriseAeroStudio.Models.Credit", "Credit")
                        .WithMany()
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Credit");
                });

            modelBuilder.Entity("EnterpriseAeroStudio.Models.ExpenseItem", b =>
                {
                    b.HasOne("EnterpriseAeroStudio.Models.CarItem", "Car")
                        .WithMany("Expenses")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Car");
                });

            modelBuilder.Entity("EnterpriseAeroStudio.Models.CarItem", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
